// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCON7Lw4HjriJm8YQZe2Q7j-Ev6n268-xE',
    appId: '1:1040317422566:web:187fe9c4f7443ebc415427',
    messagingSenderId: '1040317422566',
    projectId: 'just-chat-2025',
    authDomain: 'just-chat-2025.firebaseapp.com',
    storageBucket: 'just-chat-2025.firebasestorage.app',
    measurementId: 'G-8QN2FC80K0',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDL1uSrX0KojQw7X8VPMOvfvOaxsN8pl8s',
    appId: '1:1040317422566:android:5c3a846acd5c72d7415427',
    messagingSenderId: '1040317422566',
    projectId: 'just-chat-2025',
    storageBucket: 'just-chat-2025.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAxvYZhxNfnnLk3x6I84ItIrcQlceeqHd8',
    appId: '1:1040317422566:ios:8b8015e20b7737f0415427',
    messagingSenderId: '1040317422566',
    projectId: 'just-chat-2025',
    storageBucket: 'just-chat-2025.firebasestorage.app',
    iosBundleId: 'com.example.justChat',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAxvYZhxNfnnLk3x6I84ItIrcQlceeqHd8',
    appId: '1:1040317422566:ios:8b8015e20b7737f0415427',
    messagingSenderId: '1040317422566',
    projectId: 'just-chat-2025',
    storageBucket: 'just-chat-2025.firebasestorage.app',
    iosBundleId: 'com.example.justChat',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCON7Lw4HjriJm8YQZe2Q7j-Ev6n268-xE',
    appId: '1:1040317422566:web:230324deac1f7077415427',
    messagingSenderId: '1040317422566',
    projectId: 'just-chat-2025',
    authDomain: 'just-chat-2025.firebaseapp.com',
    storageBucket: 'just-chat-2025.firebasestorage.app',
    measurementId: 'G-1DDG5NYDT3',
  );
}
